language: go

go:
  - 1.x

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -q -y install libimage-exiftool-perl imagemagick
  - go get -v

script:
  - go generate ./...
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
