name: PicdexerCI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Environment dependencies
        run: |
          sudo apt-get -q -y install libimage-exiftool-perl imagemagick
          go version
          go install -v github.com/rakyll/statik
          go generate ./...
          go get -v
      - name: Tests
        run: go test ./...