name: PicdexerCI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.2'
      - name: Environment dependencies
        run: |
          sudo apt-get update
          sudo apt-get -q -y install libimage-exiftool-perl imagemagick
          go version
          go get -v
      - name: Tests
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Coverage publication
        run: bash <(curl -s https://codecov.io/bash)