name: Picdexer CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt-get install -y exiftool
    
    - name: Get golang dependencies
      run: go get -v -t -d ./...

    - name: Test with coverage
      run: go test -covermode=count -coverprofile=coverage.out ./...

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
      
